import os
import json
import time
import torch
import torch.distributed
from transformers import T5EncoderModel
from xfuser import xFuserFluxPipeline, xFuserArgs
from xfuser.config import FlexibleArgumentParser
from xfuser.core.distributed import (
    get_world_group,
    get_data_parallel_rank,
    get_data_parallel_world_size,
    get_runtime_state,
)

def main():
    parser = FlexibleArgumentParser(description="xFuser Arguments")
    parser.add_argument("--output_dir", type=str, default="./results", help="Directory to save generated images")
    # [ADDITION] Argument for the JSON prompt file generated by the dataset script
    parser.add_argument("--prompt_file", type=str, required=True, help="Path to the COCO prompts JSON file")
    
    args = xFuserArgs.add_cli_args(parser).parse_args()
    engine_args = xFuserArgs.from_cli_args(args)
    engine_config, input_config = engine_args.create_config()
    engine_config.runtime_config.dtype = torch.bfloat16
    
    local_rank = get_world_group().local_rank
    
    # Initialize Text Encoder
    text_encoder_2 = T5EncoderModel.from_pretrained(
        engine_config.model_config.model, 
        subfolder="text_encoder_2", 
        torch_dtype=torch.bfloat16
    )

    if args.use_fp8_t5_encoder:
        from optimum.quanto import freeze, qfloat8, quantize
        if local_rank == 0:
            print(f"Quantizing text encoder 2 to FP8...")
        quantize(text_encoder_2, weights=qfloat8)
        freeze(text_encoder_2)

    # Initialize Pipeline
    cache_args = {
        "use_teacache": engine_args.use_teacache,
        "use_fbcache": engine_args.use_fbcache,
        "rel_l1_thresh": 0.12,
        "return_hidden_states_first": False,
        "num_steps": input_config.num_inference_steps,
    }

    pipe = xFuserFluxPipeline.from_pretrained(
        pretrained_model_name_or_path=engine_config.model_config.model,
        engine_config=engine_config,
        cache_args=cache_args,
        torch_dtype=torch.bfloat16,
        text_encoder_2=text_encoder_2,
    )

    if args.enable_sequential_cpu_offload:
        pipe.enable_sequential_cpu_offload(gpu_id=local_rank)
    else:
        pipe = pipe.to(f"cuda:{local_rank}")

    # [ADDITION] Load Prompts from JSON
    if get_world_group().rank == 0:
        print(f"Loading prompts from {args.prompt_file}...")
    
    with open(args.prompt_file, 'r') as f:
        prompt_data = json.load(f)
    
    # Prepare the run once (assuming constant resolution 256x256 across all prompts)
    pipe.prepare_run(input_config, steps=input_config.num_inference_steps)

    total_prompts = len(prompt_data)
    
    # [ADDITION] Iteration Loop
    for idx, item in enumerate(prompt_data):
        prompt_id = item['id']
        prompt_text = item['prompt']
        
        if get_world_group().rank == 0:
            print(f"[{idx+1}/{total_prompts}] Processing ID {prompt_id}: {prompt_text[:50]}...")

        torch.cuda.reset_peak_memory_stats()
        
        # Generate
        # Note: We use seed + prompt_id to ensure deterministic results per image, 
        # but different noise for different images.
        start_time = time.time()
        output = pipe(
            height=input_config.height,
            width=input_config.width,
            prompt=prompt_text,
            num_inference_steps=input_config.num_inference_steps,
            output_type="pil", # Force PIL for saving
            max_sequence_length=256,
            guidance_scale=input_config.guidance_scale,
            generator=torch.Generator(device="cuda").manual_seed(input_config.seed),
            # enable_profiling=args.use_profiler,
        )
        end_time = time.time()
        elapsed_time = end_time - start_time
        # Save Logic
        # Only the last group in the pipeline should save the image
        if pipe.is_dp_last_group():
            # We assume batch_size=1 for this benchmark loop to keep ID alignment simple
            # If batch_size > 1 is used in input_config, this loop needs adjustment.
            # For FID accuracy, processing 1 by 1 is safest to match filenames.
            for i, image in enumerate(output.images):
                image_name = f"{prompt_id:05d}.png"
                save_path = os.path.join(args.output_dir, image_name)
                os.makedirs(args.output_dir, exist_ok=True)
                image.save(save_path)
                print(f"Saved: {save_path}")

    get_runtime_state().destroy_distributed_env()

if __name__ == "__main__":
    main()